version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hibernate
    environment:
      MYSQL_DATABASE: test-mysql
      MYSQL_USER: usuario1
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3008:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: